# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSair.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

# CRIA A JANELA DE RETORNAR NO CADSTRO ----v


class Ui_form_alertaDados(object):
    def setupUi(self, form_sairSystem):
        form_sairSystem.setObjectName("form_sairSystem")
        form_sairSystem.resize(321, 68)
        self.lb_quest = QtWidgets.QLabel(form_sairSystem)
        self.lb_quest.setGeometry(QtCore.QRect(20, 0, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_quest.setFont(font)
        self.lb_quest.setObjectName("lb_quest")
        self.bt_simExit = QtWidgets.QPushButton(form_sairSystem)
        self.bt_simExit.setGeometry(QtCore.QRect(110, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_simExit.setFont(font)
        self.bt_simExit.setObjectName("bt_simExit")

        font = QtGui.QFont()
        font.setPointSize(10)

        self.retranslateUi(form_sairSystem)
        QtCore.QMetaObject.connectSlotsByName(form_sairSystem)

        # BOTÕES SISTEMA
        # self.bt_simExit.clicked.connect(form_sairSystem.close)
        self.bt_simExit.clicked.connect(
            lambda: self.sairAlerta(form_sairSystem))
        # ----------------------------------------------------------------

    def retranslateUi(self, form_sairSystem):
        _translate = QtCore.QCoreApplication.translate
        form_sairSystem.setWindowTitle(_translate("form_sairSystem", "Voltar"))
        self.lb_quest.setText(_translate(
            "form_sairSystem", "Favor Inserir todos os dados nos campos!"))
        self.bt_simExit.setToolTip(_translate(
            "form_sairSystem", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_simExit.setText(_translate("form_sairSystem", "VOLTAR"))

    def sairAlerta(self, form_sairSystem):
        form_sairSystem.close()


# ----------------------------------------------------------------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_sairSystem = QtWidgets.QWidget()
    ui = Ui_form_alertaDados()
    ui.setupUi(form_sairSystem)
    form_sairSystem.show()
    sys.exit(app.exec_())
