# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# IMPORT icons
import logo_empresa
import icon_vendas
import icon_sair
import icon_receber
import icon_produtos
import icon_pagar
import icon_fornecedor
import icon_cliente
import icon_caixa
import icon_bancos

from PyQt5 import QtCore, QtGui, QtWidgets


# Import telas sistema
from cliente import Ui_formCliente
from telaSair import Ui_form_sairSystem

# ----------------------------------------------------------------


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_logoEmpresa = QtWidgets.QLabel(self.centralwidget)
        self.lb_logoEmpresa.setGeometry(QtCore.QRect(100, 70, 371, 191))
        self.lb_logoEmpresa.setStyleSheet(
            "image:url(:/logo_empresa/Icons/logo.png)")
        self.lb_logoEmpresa.setText("")
        self.lb_logoEmpresa.setObjectName("lb_logoEmpresa")
        self.bt_cliente = QtWidgets.QPushButton(self.centralwidget)
        self.bt_cliente.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.bt_cliente.setStyleSheet(
            "image:url(:/icon_cliente/Icons/cliente.png)")
        self.bt_cliente.setText("")
        self.bt_cliente.setObjectName("bt_cliente")
        self.bt_fornecedor = QtWidgets.QPushButton(self.centralwidget)
        self.bt_fornecedor.setGeometry(QtCore.QRect(70, 0, 71, 71))
        self.bt_fornecedor.setStyleSheet(
            "image:url(:/icon_fornecedor/Icons/fornecedor.png)")
        self.bt_fornecedor.setText("")
        self.bt_fornecedor.setObjectName("bt_fornecedor")
        self.bt_produtos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_produtos.setGeometry(QtCore.QRect(140, 0, 71, 71))
        self.bt_produtos.setStyleSheet(
            "image:url(:/icon_produtos/Icons/produtos.png)")
        self.bt_produtos.setText("")
        self.bt_produtos.setObjectName("bt_produtos")
        self.bt_vendas = QtWidgets.QPushButton(self.centralwidget)
        self.bt_vendas.setGeometry(QtCore.QRect(210, 0, 71, 71))
        self.bt_vendas.setStyleSheet(
            "image:url(:/icon_vendas/Icons/venda.png)")
        self.bt_vendas.setText("")
        self.bt_vendas.setObjectName("bt_vendas")
        self.bt_pagar = QtWidgets.QPushButton(self.centralwidget)
        self.bt_pagar.setGeometry(QtCore.QRect(280, 0, 71, 71))
        self.bt_pagar.setStyleSheet(
            "image:url(:/icon_pagar/Icons/contasPagar.png)")
        self.bt_pagar.setText("")
        self.bt_pagar.setObjectName("bt_pagar")
        self.bt_bancos = QtWidgets.QPushButton(self.centralwidget)
        self.bt_bancos.setGeometry(QtCore.QRect(350, 0, 71, 71))
        self.bt_bancos.setStyleSheet(
            "image:url(:/icon_bancos/Icons/banco.png)")
        self.bt_bancos.setText("")
        self.bt_bancos.setObjectName("bt_bancos")
        self.bt_receber = QtWidgets.QPushButton(self.centralwidget)
        self.bt_receber.setGeometry(QtCore.QRect(420, 0, 71, 71))
        self.bt_receber.setStyleSheet(
            "image:url(:/icon_receber/Icons/receber.png)")
        self.bt_receber.setText("")
        self.bt_receber.setObjectName("bt_receber")
        self.bt_caixa = QtWidgets.QPushButton(self.centralwidget)
        self.bt_caixa.setGeometry(QtCore.QRect(490, 0, 71, 71))
        self.bt_caixa.setStyleSheet("image:url(:/icon_caixa/Icons/caixa.png)")
        self.bt_caixa.setText("")
        self.bt_caixa.setObjectName("bt_caixa")
        self.bt_sair = QtWidgets.QPushButton(self.centralwidget)
        self.bt_sair.setGeometry(QtCore.QRect(590, 0, 51, 51))
        self.bt_sair.setStyleSheet("image:url(:/icon_sair/Icons/sair.png)")
        self.bt_sair.setText("")
        self.bt_sair.setObjectName("bt_sair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menubar.setObjectName("menubar")
        self.menuCadastros = QtWidgets.QMenu(self.menubar)
        self.menuCadastros.setObjectName("menuCadastros")
        self.menuOperecoes = QtWidgets.QMenu(self.menubar)
        self.menuOperecoes.setObjectName("menuOperecoes")
        self.menuSa_das_de_produtos = QtWidgets.QMenu(self.menuOperecoes)
        self.menuSa_das_de_produtos.setObjectName("menuSa_das_de_produtos")
        self.menuEstoque = QtWidgets.QMenu(self.menuOperecoes)
        self.menuEstoque.setObjectName("menuEstoque")
        self.menuCompras = QtWidgets.QMenu(self.menuOperecoes)
        self.menuCompras.setObjectName("menuCompras")
        self.menuFinanceiro = QtWidgets.QMenu(self.menubar)
        self.menuFinanceiro.setObjectName("menuFinanceiro")
        self.menuConsultas = QtWidgets.QMenu(self.menubar)
        self.menuConsultas.setObjectName("menuConsultas")
        self.menuVendas = QtWidgets.QMenu(self.menuConsultas)
        self.menuVendas.setObjectName("menuVendas")
        self.menuConsumo = QtWidgets.QMenu(self.menuConsultas)
        self.menuConsumo.setObjectName("menuConsumo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCliente = QtWidgets.QAction(MainWindow)
        self.actionCliente.setObjectName("actionCliente")
        self.actionFornecedor = QtWidgets.QAction(MainWindow)
        self.actionFornecedor.setObjectName("actionFornecedor")
        self.actionUsuario = QtWidgets.QAction(MainWindow)
        self.actionUsuario.setObjectName("actionUsuario")
        self.actionVenda = QtWidgets.QAction(MainWindow)
        self.actionVenda.setObjectName("actionVenda")
        self.actionConsumo = QtWidgets.QAction(MainWindow)
        self.actionConsumo.setObjectName("actionConsumo")
        self.actionSaldo = QtWidgets.QAction(MainWindow)
        self.actionSaldo.setObjectName("actionSaldo")
        self.actionCompras_2 = QtWidgets.QAction(MainWindow)
        self.actionCompras_2.setObjectName("actionCompras_2")
        self.actionPedido = QtWidgets.QAction(MainWindow)
        self.actionPedido.setObjectName("actionPedido")
        self.actionCancelar = QtWidgets.QAction(MainWindow)
        self.actionCancelar.setObjectName("actionCancelar")
        self.actionCaixa = QtWidgets.QAction(MainWindow)
        self.actionCaixa.setObjectName("actionCaixa")
        self.actionContas_Banco = QtWidgets.QAction(MainWindow)
        self.actionContas_Banco.setObjectName("actionContas_Banco")
        self.actionContas_pagar = QtWidgets.QAction(MainWindow)
        self.actionContas_pagar.setObjectName("actionContas_pagar")
        self.actionContas_pagas = QtWidgets.QAction(MainWindow)
        self.actionContas_pagas.setObjectName("actionContas_pagas")
        self.actionContas_receber = QtWidgets.QAction(MainWindow)
        self.actionContas_receber.setObjectName("actionContas_receber")
        self.actionContas_recebidas = QtWidgets.QAction(MainWindow)
        self.actionContas_recebidas.setObjectName("actionContas_recebidas")
        self.actionGeral = QtWidgets.QAction(MainWindow)
        self.actionGeral.setObjectName("actionGeral")
        self.actionResumido = QtWidgets.QAction(MainWindow)
        self.actionResumido.setObjectName("actionResumido")
        self.actionGeral_2 = QtWidgets.QAction(MainWindow)
        self.actionGeral_2.setObjectName("actionGeral_2")
        self.actionResumido_2 = QtWidgets.QAction(MainWindow)
        self.actionResumido_2.setObjectName("actionResumido_2")
        self.menuCadastros.addAction(self.actionCliente)
        self.menuCadastros.addAction(self.actionFornecedor)
        self.menuCadastros.addAction(self.actionUsuario)
        self.menuSa_das_de_produtos.addAction(self.actionVenda)
        self.menuSa_das_de_produtos.addAction(self.actionConsumo)
        self.menuEstoque.addAction(self.actionSaldo)
        self.menuCompras.addAction(self.actionCompras_2)
        self.menuCompras.addAction(self.actionPedido)
        self.menuCompras.addAction(self.actionCancelar)
        self.menuOperecoes.addAction(self.menuSa_das_de_produtos.menuAction())
        self.menuOperecoes.addAction(self.menuEstoque.menuAction())
        self.menuOperecoes.addAction(self.menuCompras.menuAction())
        self.menuFinanceiro.addAction(self.actionCaixa)
        self.menuFinanceiro.addAction(self.actionContas_Banco)
        self.menuFinanceiro.addAction(self.actionContas_pagar)
        self.menuFinanceiro.addAction(self.actionContas_pagas)
        self.menuFinanceiro.addAction(self.actionContas_receber)
        self.menuFinanceiro.addAction(self.actionContas_recebidas)
        self.menuVendas.addAction(self.actionGeral)
        self.menuVendas.addAction(self.actionResumido)
        self.menuConsumo.addAction(self.actionGeral_2)
        self.menuConsumo.addAction(self.actionResumido_2)
        self.menuConsultas.addAction(self.menuVendas.menuAction())
        self.menuConsultas.addAction(self.menuConsumo.menuAction())
        self.menubar.addAction(self.menuCadastros.menuAction())
        self.menubar.addAction(self.menuOperecoes.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        """ self.bt_cliente.clicked.connect(self.cliente)
        self.bt_fornecedor.clicked.connect(self.fornecedor)
        self.bt_produtos.clicked.connect(self.produtos)
        self.bt_vendas.clicked.connect(self.vendas)
        self.bt_pagar.clicked.connect(self.pagar)
        self.bt_bancos.clicked.connect(self.bancos) """

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_logoEmpresa.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_cliente.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_fornecedor.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_produtos.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_vendas.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_pagar.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_bancos.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_receber.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_caixa.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_sair.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.menuCadastros.setTitle(_translate("MainWindow", "Cadastros"))
        self.menuOperecoes.setTitle(_translate("MainWindow", "Operecoes"))
        self.menuSa_das_de_produtos.setTitle(
            _translate("MainWindow", "Saídas de produtos"))
        self.menuEstoque.setTitle(_translate("MainWindow", "Estoque"))
        self.menuCompras.setTitle(_translate("MainWindow", "Compras"))
        self.menuFinanceiro.setTitle(_translate("MainWindow", "Financeiro"))
        self.menuConsultas.setTitle(_translate("MainWindow", "Consultas"))
        self.menuVendas.setTitle(_translate("MainWindow", "Vendas"))
        self.menuConsumo.setTitle(_translate("MainWindow", "Consumo"))
        self.actionCliente.setText(_translate("MainWindow", "Cliente"))
        self.actionFornecedor.setText(_translate("MainWindow", "Fornecedor"))
        self.actionUsuario.setText(_translate("MainWindow", "Usuários"))
        self.actionVenda.setText(_translate("MainWindow", "Venda"))
        self.actionConsumo.setText(_translate("MainWindow", "Consumo"))
        self.actionSaldo.setText(_translate("MainWindow", "Saldo"))
        self.actionCompras_2.setText(_translate("MainWindow", "Comprar"))
        self.actionPedido.setText(_translate("MainWindow", "Pedido"))
        self.actionCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.actionCaixa.setText(_translate("MainWindow", "Caixa"))
        self.actionContas_Banco.setText(
            _translate("MainWindow", "Contas Banco"))
        self.actionContas_pagar.setText(
            _translate("MainWindow", "Contas pagar"))
        self.actionContas_pagas.setText(
            _translate("MainWindow", "Contas pagas"))
        self.actionContas_receber.setText(
            _translate("MainWindow", "Contas receber"))
        self.actionContas_recebidas.setText(
            _translate("MainWindow", "Contas recebidas"))
        self.actionGeral.setText(_translate("MainWindow", "Geral"))
        self.actionResumido.setText(_translate("MainWindow", "Resumido"))
        self.actionGeral_2.setText(_translate("MainWindow", "Geral"))
        self.actionResumido_2.setText(_translate("MainWindow", "Resumido"))

# ----------------------------------------------------------------
        # BOTÕES SISTEMA
        self.bt_sair.clicked.connect(self.sairSistema)  # Fecha o sistema
        self.bt_cliente.clicked.connect(
            self.telaCliente)  # Botão abre a telaCliente
        self.actionCliente.triggered.connect(
            self.telaCliente)  # menuCliente abre a telaCliente

# ----------------------------------------------------------------
    # FUNÇOES SISTEMA

    # Fechar Sistema
    def sairSistema(self):
        self.form_sairSystem = QtWidgets.QWidget()
        self.ui = Ui_form_sairSystem()
        self.ui.setupUi(self.form_sairSystem)
        self.form_sairSystem.show()
        # sys.exit()

    # Abre tela cliente

    def telaCliente(self):
        self.formCliente = QtWidgets.QWidget()
        self.ui = Ui_formCliente()
        self.ui.setupUi(self.formCliente)
        self.formCliente.show()


# ----------------------------------------------------------------
# Imagens do Sistema--------v
# ----------------------------------------------------------------

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
