# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaSair.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


import sys


class Ui_form_sairSystem(object):
    def setupUi(self, form_sairSystem):
        form_sairSystem.setObjectName("form_sairSystem")
        form_sairSystem.resize(221, 68)
        self.lb_quest = QtWidgets.QLabel(form_sairSystem)
        self.lb_quest.setGeometry(QtCore.QRect(10, 0, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_quest.setFont(font)
        self.lb_quest.setObjectName("lb_quest")
        self.bt_simExit = QtWidgets.QPushButton(form_sairSystem)
        self.bt_simExit.setGeometry(QtCore.QRect(40, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_simExit.setFont(font)
        self.bt_simExit.setObjectName("bt_simExit")
        self.bt_naoExit = QtWidgets.QPushButton(form_sairSystem)
        self.bt_naoExit.setGeometry(QtCore.QRect(120, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_naoExit.setFont(font)
        self.bt_naoExit.setObjectName("bt_naoExit")

        self.retranslateUi(form_sairSystem)
        QtCore.QMetaObject.connectSlotsByName(form_sairSystem)

        # BOTÕES SISTEMA
        self.bt_simExit.clicked.connect(self.exitSistema)
        self.bt_naoExit.clicked.connect(form_sairSystem.close)
# ----------------------------------------------------------------

    def retranslateUi(self, form_sairSystem):
        _translate = QtCore.QCoreApplication.translate
        form_sairSystem.setWindowTitle(_translate("form_sairSystem", "Form"))
        self.lb_quest.setText(_translate(
            "form_sairSystem", "Tem certeza que deseja sair?"))
        self.bt_simExit.setToolTip(_translate(
            "form_sairSystem", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_simExit.setText(_translate("form_sairSystem", "SIM"))
        self.bt_naoExit.setToolTip(_translate(
            "form_sairSystem", "<html><head/><body><p><br/></p></body></html>"))
        self.bt_naoExit.setText(_translate("form_sairSystem", "NÃO"))
# ----------------------------------------------------------------

    # Fecha o sistema
    def exitSistema(self):
        sys.exit()

    # Volta para o menu principal
    # def backSistema(self):


# ----------------------------------------------------------------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_sairSystem = QtWidgets.QWidget()
    ui = Ui_form_sairSystem()
    ui.setupUi(form_sairSystem)
    form_sairSystem.show()
    sys.exit(app.exec_())
